MR-7 Added steps to install MinGw c/c++ complier to the README.md
SuchithSridhar/RTS-Minesweeper pull request #1
Opened 2022-10-27 23:35 UTC by BrahmpreetSingh07

2022-10-27 23:48 UTC, Porkius commented on README.md
> +Windows setup:[link]
What is the [link] specifying?

2022-10-27 23:51 UTC, Porkius requested changes
Good work! The only issue I see is on line 11, which uses a placeholder "link" name. Other than that I believe it is good to merge.

2022-10-28 03:02 UTC, Porkius approved these changes
Looks good! I think it's ready to be merged!

2022-10-28 03:33 UTC, SuchithSridhar commented
Looks good, merging.

2022-10-28 03:44 UTC, SuchithSridhar approved these changes
Looks good, merging.

2022-10-28 03:45 UTC, merged